---

- name: configurate_files
  hosts: all
  become: yes

  tasks:

    - name: Create_work_dir
      ansible.builtin.file:
        path: /var/wiki
        state: directory

    - name: Extract wiki-js.tar.gz into /var/wiki
      ansible.builtin.unarchive:
        src: /home/wiki-js.tar.gz
        dest: /var/wiki
        remote_src: yes

    - name: Change_the_working_directory
      ansible.builtin.shell:
        cmd: mv config.sample.yml config.yml
        chdir: /var/wiki

    - name: Change pass_to_connetcion_data_base
      ansible.builtin.lineinfile:
        dest: /var/wiki/config.yml
        regexp: '^  pass: wikijsrocks'
        line: "  pass: 12345"

    - name: start wikijs_server
      ansible.builtin.shell:
        cmd: node server
        chdir: /var/wiki

    - name: Change pass_to_connetcion_data_base
      ansible.builtin.lineinfile:
        dest: /var/wiki/config.yml
        regexp: '^  user: wikijs'
        line: "  user: wiki"
