---
- name: get_url module demo
  hosts: all
  become: yes

  tasks:
    - name: download file
      ansible.builtin.get_url:
        url: "https://github.com/Requarks/wiki/releases/latest/download/wiki-js.tar.gz"
        dest: "/home"
        mode: '0666'
