---
# handlers file for deploy_wiki
- name: Enable Postgresql
  ansible.builtin.systemd_service:
    name: postgresql.service
    enabled: true
    masked: no

- name: Restart wiki.service, also issue daemon-reload to pick up config changes
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: wiki.service

- name: Enable service and ensure it is not masked
  ansible.builtin.systemd_service:
    name: wiki.service
    enabled: true
    masked: no
